azure:
  service-bus:
    connection-string: Endpoint=sb://ndp-uat-dhp-fhir-sbus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=BLp3m3+RQlFbLxDnQyUWi3QYGrGfMQrvvFhjohj5B0g=
    queue-name: dhp-service-bus-queue